// @ts-nocheck
// source: proto/LogIn.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

// var jspb = require('google-protobuf');
import * as jspb from 'google-protobuf'
var goog = jspb
var global =
  (typeof globalThis !== 'undefined' && globalThis) ||
  (typeof window !== 'undefined' && window) ||
  (typeof global !== 'undefined' && global) ||
  (typeof self !== 'undefined' && self) ||
  function () {
    return this
  }.call(null) ||
  Function('return this')()

goog.exportSymbol('proto.LogIn', null, global)
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.LogIn = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.LogIn, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.LogIn.displayName = 'proto.LogIn'
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.LogIn.prototype.toObject = function (opt_includeInstance) {
    return proto.LogIn.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.LogIn} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.LogIn.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        login: jspb.Message.getFieldWithDefault(msg, 1, 0),
        pwd: jspb.Message.getFieldWithDefault(msg, 2, ''),
        device: jspb.Message.getFieldWithDefault(msg, 3, 0)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.LogIn}
 */
proto.LogIn.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.LogIn()
  return proto.LogIn.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.LogIn} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.LogIn}
 */
proto.LogIn.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {number} */ reader.readUint64()
        msg.setLogin(value)
        break
      case 2:
        var value = /** @type {string} */ reader.readString()
        msg.setPwd(value)
        break
      case 3:
        var value = /** @type {number} */ reader.readUint32()
        msg.setDevice(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.LogIn.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.LogIn.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.LogIn} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LogIn.serializeBinaryToWriter = function (message, writer) {
  var f = undefined
  f = message.getLogin()
  if (f !== 0) {
    writer.writeUint64(1, f)
  }
  f = message.getPwd()
  if (f.length > 0) {
    writer.writeString(2, f)
  }
  f = message.getDevice()
  if (f !== 0) {
    writer.writeUint32(3, f)
  }
}

/**
 * optional uint64 login = 1;
 * @return {number}
 */
proto.LogIn.prototype.getLogin = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 1, 0)
}

/**
 * @param {number} value
 * @return {!proto.LogIn} returns this
 */
proto.LogIn.prototype.setLogin = function (value) {
  return jspb.Message.setProto3IntField(this, 1, value)
}

/**
 * optional string pwd = 2;
 * @return {string}
 */
proto.LogIn.prototype.getPwd = function () {
  return /** @type {string} */ jspb.Message.getFieldWithDefault(this, 2, '')
}

/**
 * @param {string} value
 * @return {!proto.LogIn} returns this
 */
proto.LogIn.prototype.setPwd = function (value) {
  return jspb.Message.setProto3StringField(this, 2, value)
}

/**
 * optional uint32 device = 3;
 * @return {number}
 */
proto.LogIn.prototype.getDevice = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 3, 0)
}

/**
 * @param {number} value
 * @return {!proto.LogIn} returns this
 */
proto.LogIn.prototype.setDevice = function (value) {
  return jspb.Message.setProto3IntField(this, 3, value)
}

// goog.object.extend(exports, proto);
export default proto
