// @ts-nocheck
// source: MtQuest.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

// var jspb = require('google-protobuf');
import * as jspb from 'google-protobuf'
var goog = jspb
var global =
  (typeof globalThis !== 'undefined' && globalThis) ||
  (typeof window !== 'undefined' && window) ||
  (typeof global !== 'undefined' && global) ||
  (typeof self !== 'undefined' && self) ||
  function () {
    return this
  }.call(null) ||
  Function('return this')()

goog.exportSymbol('proto.com.ud.xcloud.mt5.proto.ModOrder', null, global)
goog.exportSymbol('proto.com.ud.xcloud.mt5.proto.ModPos', null, global)
goog.exportSymbol('proto.com.ud.xcloud.mt5.proto.NewOrder', null, global)
goog.exportSymbol('proto.com.ud.xcloud.mt5.proto.QSymbol', null, global)
goog.exportSymbol('proto.com.ud.xcloud.mt5.proto.Response', null, global)
goog.exportSymbol('proto.com.ud.xcloud.mt5.proto.Subscribe', null, global)
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.ud.xcloud.mt5.proto.NewOrder = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.com.ud.xcloud.mt5.proto.NewOrder, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.ud.xcloud.mt5.proto.NewOrder.displayName = 'proto.com.ud.xcloud.mt5.proto.NewOrder'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.ud.xcloud.mt5.proto.ModOrder = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.com.ud.xcloud.mt5.proto.ModOrder, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.ud.xcloud.mt5.proto.ModOrder.displayName = 'proto.com.ud.xcloud.mt5.proto.ModOrder'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.ud.xcloud.mt5.proto.ModPos = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.com.ud.xcloud.mt5.proto.ModPos, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.ud.xcloud.mt5.proto.ModPos.displayName = 'proto.com.ud.xcloud.mt5.proto.ModPos'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.ud.xcloud.mt5.proto.QSymbol = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.com.ud.xcloud.mt5.proto.QSymbol, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.ud.xcloud.mt5.proto.QSymbol.displayName = 'proto.com.ud.xcloud.mt5.proto.QSymbol'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.ud.xcloud.mt5.proto.Subscribe = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.ud.xcloud.mt5.proto.Subscribe.repeatedFields_, null)
}
goog.inherits(proto.com.ud.xcloud.mt5.proto.Subscribe, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.ud.xcloud.mt5.proto.Subscribe.displayName = 'proto.com.ud.xcloud.mt5.proto.Subscribe'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.ud.xcloud.mt5.proto.Response = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.com.ud.xcloud.mt5.proto.Response, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.ud.xcloud.mt5.proto.Response.displayName = 'proto.com.ud.xcloud.mt5.proto.Response'
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.toObject = function (opt_includeInstance) {
    return proto.com.ud.xcloud.mt5.proto.NewOrder.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.com.ud.xcloud.mt5.proto.NewOrder} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.com.ud.xcloud.mt5.proto.NewOrder.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        ip: jspb.Message.getFieldWithDefault(msg, 1, ''),
        sbl: jspb.Message.getFieldWithDefault(msg, 2, ''),
        act: jspb.Message.getFieldWithDefault(msg, 3, 0),
        type: jspb.Message.getFieldWithDefault(msg, 4, 0),
        price: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
        vol: jspb.Message.getFieldWithDefault(msg, 6, 0),
        sl: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
        tp: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
        position: jspb.Message.getFieldWithDefault(msg, 9, 0),
        positionby: jspb.Message.getFieldWithDefault(msg, 10, 0)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.ud.xcloud.mt5.proto.NewOrder}
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.com.ud.xcloud.mt5.proto.NewOrder()
  return proto.com.ud.xcloud.mt5.proto.NewOrder.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.ud.xcloud.mt5.proto.NewOrder} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.ud.xcloud.mt5.proto.NewOrder}
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {string} */ reader.readString()
        msg.setIp(value)
        break
      case 2:
        var value = /** @type {string} */ reader.readString()
        msg.setSbl(value)
        break
      case 3:
        var value = /** @type {number} */ reader.readInt32()
        msg.setAct(value)
        break
      case 4:
        var value = /** @type {number} */ reader.readInt32()
        msg.setType(value)
        break
      case 5:
        var value = /** @type {number} */ reader.readDouble()
        msg.setPrice(value)
        break
      case 6:
        var value = /** @type {number} */ reader.readUint64()
        msg.setVol(value)
        break
      case 7:
        var value = /** @type {number} */ reader.readDouble()
        msg.setSl(value)
        break
      case 8:
        var value = /** @type {number} */ reader.readDouble()
        msg.setTp(value)
        break
      case 9:
        var value = /** @type {number} */ reader.readUint64()
        msg.setPosition(value)
        break
      case 10:
        var value = /** @type {number} */ reader.readUint64()
        msg.setPositionby(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.com.ud.xcloud.mt5.proto.NewOrder.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.ud.xcloud.mt5.proto.NewOrder} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.serializeBinaryToWriter = function (message, writer) {
  var f = undefined
  f = /** @type {string} */ jspb.Message.getField(message, 1)
  if (f != null) {
    writer.writeString(1, f)
  }
  f = message.getSbl()
  if (f.length > 0) {
    writer.writeString(2, f)
  }
  f = message.getAct()
  if (f !== 0) {
    writer.writeInt32(3, f)
  }
  f = message.getType()
  if (f !== 0) {
    writer.writeInt32(4, f)
  }
  f = message.getPrice()
  if (f !== 0.0) {
    writer.writeDouble(5, f)
  }
  f = message.getVol()
  if (f !== 0) {
    writer.writeUint64(6, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 7)
  if (f != null) {
    writer.writeDouble(7, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 8)
  if (f != null) {
    writer.writeDouble(8, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 9)
  if (f != null) {
    writer.writeUint64(9, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 10)
  if (f != null) {
    writer.writeUint64(10, f)
  }
}

/**
 * optional string ip = 1;
 * @return {string}
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.getIp = function () {
  return /** @type {string} */ jspb.Message.getFieldWithDefault(this, 1, '')
}

/**
 * @param {string} value
 * @return {!proto.com.ud.xcloud.mt5.proto.NewOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.setIp = function (value) {
  return jspb.Message.setField(this, 1, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.NewOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.clearIp = function () {
  return jspb.Message.setField(this, 1, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.hasIp = function () {
  return jspb.Message.getField(this, 1) != null
}

/**
 * optional string sbl = 2;
 * @return {string}
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.getSbl = function () {
  return /** @type {string} */ jspb.Message.getFieldWithDefault(this, 2, '')
}

/**
 * @param {string} value
 * @return {!proto.com.ud.xcloud.mt5.proto.NewOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.setSbl = function (value) {
  return jspb.Message.setProto3StringField(this, 2, value)
}

/**
 * optional int32 act = 3;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.getAct = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 3, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.NewOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.setAct = function (value) {
  return jspb.Message.setProto3IntField(this, 3, value)
}

/**
 * optional int32 type = 4;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.getType = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 4, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.NewOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.setType = function (value) {
  return jspb.Message.setProto3IntField(this, 4, value)
}

/**
 * optional double price = 5;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.getPrice = function () {
  return /** @type {number} */ jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.NewOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.setPrice = function (value) {
  return jspb.Message.setProto3FloatField(this, 5, value)
}

/**
 * optional uint64 vol = 6;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.getVol = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 6, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.NewOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.setVol = function (value) {
  return jspb.Message.setProto3IntField(this, 6, value)
}

/**
 * optional double sl = 7;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.getSl = function () {
  return /** @type {number} */ jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.NewOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.setSl = function (value) {
  return jspb.Message.setField(this, 7, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.NewOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.clearSl = function () {
  return jspb.Message.setField(this, 7, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.hasSl = function () {
  return jspb.Message.getField(this, 7) != null
}

/**
 * optional double tp = 8;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.getTp = function () {
  return /** @type {number} */ jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.NewOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.setTp = function (value) {
  return jspb.Message.setField(this, 8, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.NewOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.clearTp = function () {
  return jspb.Message.setField(this, 8, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.hasTp = function () {
  return jspb.Message.getField(this, 8) != null
}

/**
 * optional uint64 position = 9;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.getPosition = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 9, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.NewOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.setPosition = function (value) {
  return jspb.Message.setField(this, 9, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.NewOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.clearPosition = function () {
  return jspb.Message.setField(this, 9, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.hasPosition = function () {
  return jspb.Message.getField(this, 9) != null
}

/**
 * optional uint64 positionBy = 10;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.getPositionby = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 10, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.NewOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.setPositionby = function (value) {
  return jspb.Message.setField(this, 10, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.NewOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.clearPositionby = function () {
  return jspb.Message.setField(this, 10, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.NewOrder.prototype.hasPositionby = function () {
  return jspb.Message.getField(this, 10) != null
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.com.ud.xcloud.mt5.proto.ModOrder.prototype.toObject = function (opt_includeInstance) {
    return proto.com.ud.xcloud.mt5.proto.ModOrder.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.com.ud.xcloud.mt5.proto.ModOrder} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.com.ud.xcloud.mt5.proto.ModOrder.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        ticket: jspb.Message.getFieldWithDefault(msg, 1, 0),
        price: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
        sl: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
        tp: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.ud.xcloud.mt5.proto.ModOrder}
 */
proto.com.ud.xcloud.mt5.proto.ModOrder.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.com.ud.xcloud.mt5.proto.ModOrder()
  return proto.com.ud.xcloud.mt5.proto.ModOrder.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.ud.xcloud.mt5.proto.ModOrder} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.ud.xcloud.mt5.proto.ModOrder}
 */
proto.com.ud.xcloud.mt5.proto.ModOrder.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {number} */ reader.readUint64()
        msg.setTicket(value)
        break
      case 2:
        var value = /** @type {number} */ reader.readDouble()
        msg.setPrice(value)
        break
      case 3:
        var value = /** @type {number} */ reader.readDouble()
        msg.setSl(value)
        break
      case 4:
        var value = /** @type {number} */ reader.readDouble()
        msg.setTp(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.ud.xcloud.mt5.proto.ModOrder.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.com.ud.xcloud.mt5.proto.ModOrder.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.ud.xcloud.mt5.proto.ModOrder} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.ud.xcloud.mt5.proto.ModOrder.serializeBinaryToWriter = function (message, writer) {
  var f = undefined
  f = message.getTicket()
  if (f !== 0) {
    writer.writeUint64(1, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 2)
  if (f != null) {
    writer.writeDouble(2, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 3)
  if (f != null) {
    writer.writeDouble(3, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 4)
  if (f != null) {
    writer.writeDouble(4, f)
  }
}

/**
 * optional uint64 ticket = 1;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.ModOrder.prototype.getTicket = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 1, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.ModOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.ModOrder.prototype.setTicket = function (value) {
  return jspb.Message.setProto3IntField(this, 1, value)
}

/**
 * optional double price = 2;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.ModOrder.prototype.getPrice = function () {
  return /** @type {number} */ jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.ModOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.ModOrder.prototype.setPrice = function (value) {
  return jspb.Message.setField(this, 2, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.ModOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.ModOrder.prototype.clearPrice = function () {
  return jspb.Message.setField(this, 2, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.ModOrder.prototype.hasPrice = function () {
  return jspb.Message.getField(this, 2) != null
}

/**
 * optional double sl = 3;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.ModOrder.prototype.getSl = function () {
  return /** @type {number} */ jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.ModOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.ModOrder.prototype.setSl = function (value) {
  return jspb.Message.setField(this, 3, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.ModOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.ModOrder.prototype.clearSl = function () {
  return jspb.Message.setField(this, 3, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.ModOrder.prototype.hasSl = function () {
  return jspb.Message.getField(this, 3) != null
}

/**
 * optional double tp = 4;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.ModOrder.prototype.getTp = function () {
  return /** @type {number} */ jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.ModOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.ModOrder.prototype.setTp = function (value) {
  return jspb.Message.setField(this, 4, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.ModOrder} returns this
 */
proto.com.ud.xcloud.mt5.proto.ModOrder.prototype.clearTp = function () {
  return jspb.Message.setField(this, 4, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.ModOrder.prototype.hasTp = function () {
  return jspb.Message.getField(this, 4) != null
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.com.ud.xcloud.mt5.proto.ModPos.prototype.toObject = function (opt_includeInstance) {
    return proto.com.ud.xcloud.mt5.proto.ModPos.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.com.ud.xcloud.mt5.proto.ModPos} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.com.ud.xcloud.mt5.proto.ModPos.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        ticket: jspb.Message.getFieldWithDefault(msg, 1, 0),
        sl: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
        tp: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.ud.xcloud.mt5.proto.ModPos}
 */
proto.com.ud.xcloud.mt5.proto.ModPos.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.com.ud.xcloud.mt5.proto.ModPos()
  return proto.com.ud.xcloud.mt5.proto.ModPos.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.ud.xcloud.mt5.proto.ModPos} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.ud.xcloud.mt5.proto.ModPos}
 */
proto.com.ud.xcloud.mt5.proto.ModPos.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {number} */ reader.readUint64()
        msg.setTicket(value)
        break
      case 2:
        var value = /** @type {number} */ reader.readDouble()
        msg.setSl(value)
        break
      case 3:
        var value = /** @type {number} */ reader.readDouble()
        msg.setTp(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.ud.xcloud.mt5.proto.ModPos.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.com.ud.xcloud.mt5.proto.ModPos.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.ud.xcloud.mt5.proto.ModPos} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.ud.xcloud.mt5.proto.ModPos.serializeBinaryToWriter = function (message, writer) {
  var f = undefined
  f = message.getTicket()
  if (f !== 0) {
    writer.writeUint64(1, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 2)
  if (f != null) {
    writer.writeDouble(2, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 3)
  if (f != null) {
    writer.writeDouble(3, f)
  }
}

/**
 * optional uint64 ticket = 1;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.ModPos.prototype.getTicket = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 1, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.ModPos} returns this
 */
proto.com.ud.xcloud.mt5.proto.ModPos.prototype.setTicket = function (value) {
  return jspb.Message.setProto3IntField(this, 1, value)
}

/**
 * optional double sl = 2;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.ModPos.prototype.getSl = function () {
  return /** @type {number} */ jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.ModPos} returns this
 */
proto.com.ud.xcloud.mt5.proto.ModPos.prototype.setSl = function (value) {
  return jspb.Message.setField(this, 2, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.ModPos} returns this
 */
proto.com.ud.xcloud.mt5.proto.ModPos.prototype.clearSl = function () {
  return jspb.Message.setField(this, 2, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.ModPos.prototype.hasSl = function () {
  return jspb.Message.getField(this, 2) != null
}

/**
 * optional double tp = 3;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.ModPos.prototype.getTp = function () {
  return /** @type {number} */ jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.ModPos} returns this
 */
proto.com.ud.xcloud.mt5.proto.ModPos.prototype.setTp = function (value) {
  return jspb.Message.setField(this, 3, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.ModPos} returns this
 */
proto.com.ud.xcloud.mt5.proto.ModPos.prototype.clearTp = function () {
  return jspb.Message.setField(this, 3, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.ModPos.prototype.hasTp = function () {
  return jspb.Message.getField(this, 3) != null
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.com.ud.xcloud.mt5.proto.QSymbol.prototype.toObject = function (opt_includeInstance) {
    return proto.com.ud.xcloud.mt5.proto.QSymbol.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.com.ud.xcloud.mt5.proto.QSymbol} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.com.ud.xcloud.mt5.proto.QSymbol.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        ip: jspb.Message.getFieldWithDefault(msg, 1, ''),
        sbl: jspb.Message.getFieldWithDefault(msg, 2, '')
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.ud.xcloud.mt5.proto.QSymbol}
 */
proto.com.ud.xcloud.mt5.proto.QSymbol.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.com.ud.xcloud.mt5.proto.QSymbol()
  return proto.com.ud.xcloud.mt5.proto.QSymbol.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.ud.xcloud.mt5.proto.QSymbol} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.ud.xcloud.mt5.proto.QSymbol}
 */
proto.com.ud.xcloud.mt5.proto.QSymbol.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {string} */ reader.readString()
        msg.setIp(value)
        break
      case 2:
        var value = /** @type {string} */ reader.readString()
        msg.setSbl(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.ud.xcloud.mt5.proto.QSymbol.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.com.ud.xcloud.mt5.proto.QSymbol.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.ud.xcloud.mt5.proto.QSymbol} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.ud.xcloud.mt5.proto.QSymbol.serializeBinaryToWriter = function (message, writer) {
  var f = undefined
  f = /** @type {string} */ jspb.Message.getField(message, 1)
  if (f != null) {
    writer.writeString(1, f)
  }
  f = message.getSbl()
  if (f.length > 0) {
    writer.writeString(2, f)
  }
}

/**
 * optional string ip = 1;
 * @return {string}
 */
proto.com.ud.xcloud.mt5.proto.QSymbol.prototype.getIp = function () {
  return /** @type {string} */ jspb.Message.getFieldWithDefault(this, 1, '')
}

/**
 * @param {string} value
 * @return {!proto.com.ud.xcloud.mt5.proto.QSymbol} returns this
 */
proto.com.ud.xcloud.mt5.proto.QSymbol.prototype.setIp = function (value) {
  return jspb.Message.setField(this, 1, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.QSymbol} returns this
 */
proto.com.ud.xcloud.mt5.proto.QSymbol.prototype.clearIp = function () {
  return jspb.Message.setField(this, 1, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.QSymbol.prototype.hasIp = function () {
  return jspb.Message.getField(this, 1) != null
}

/**
 * optional string sbl = 2;
 * @return {string}
 */
proto.com.ud.xcloud.mt5.proto.QSymbol.prototype.getSbl = function () {
  return /** @type {string} */ jspb.Message.getFieldWithDefault(this, 2, '')
}

/**
 * @param {string} value
 * @return {!proto.com.ud.xcloud.mt5.proto.QSymbol} returns this
 */
proto.com.ud.xcloud.mt5.proto.QSymbol.prototype.setSbl = function (value) {
  return jspb.Message.setProto3StringField(this, 2, value)
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.ud.xcloud.mt5.proto.Subscribe.repeatedFields_ = [1]

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.com.ud.xcloud.mt5.proto.Subscribe.prototype.toObject = function (opt_includeInstance) {
    return proto.com.ud.xcloud.mt5.proto.Subscribe.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.com.ud.xcloud.mt5.proto.Subscribe} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.com.ud.xcloud.mt5.proto.Subscribe.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        sblsList: jspb.Message.toObjectList(msg.getSblsList(), proto.com.ud.xcloud.mt5.proto.QSymbol.toObject, includeInstance)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.ud.xcloud.mt5.proto.Subscribe}
 */
proto.com.ud.xcloud.mt5.proto.Subscribe.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.com.ud.xcloud.mt5.proto.Subscribe()
  return proto.com.ud.xcloud.mt5.proto.Subscribe.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.ud.xcloud.mt5.proto.Subscribe} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.ud.xcloud.mt5.proto.Subscribe}
 */
proto.com.ud.xcloud.mt5.proto.Subscribe.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = new proto.com.ud.xcloud.mt5.proto.QSymbol()
        reader.readMessage(value, proto.com.ud.xcloud.mt5.proto.QSymbol.deserializeBinaryFromReader)
        msg.addSbls(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.ud.xcloud.mt5.proto.Subscribe.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.com.ud.xcloud.mt5.proto.Subscribe.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.ud.xcloud.mt5.proto.Subscribe} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.ud.xcloud.mt5.proto.Subscribe.serializeBinaryToWriter = function (message, writer) {
  var f = undefined
  f = message.getSblsList()
  if (f.length > 0) {
    writer.writeRepeatedMessage(1, f, proto.com.ud.xcloud.mt5.proto.QSymbol.serializeBinaryToWriter)
  }
}

/**
 * repeated QSymbol sbls = 1;
 * @return {!Array<!proto.com.ud.xcloud.mt5.proto.QSymbol>}
 */
proto.com.ud.xcloud.mt5.proto.Subscribe.prototype.getSblsList = function () {
  return /** @type{!Array<!proto.com.ud.xcloud.mt5.proto.QSymbol>} */ jspb.Message.getRepeatedWrapperField(
    this,
    proto.com.ud.xcloud.mt5.proto.QSymbol,
    1
  )
}

/**
 * @param {!Array<!proto.com.ud.xcloud.mt5.proto.QSymbol>} value
 * @return {!proto.com.ud.xcloud.mt5.proto.Subscribe} returns this
 */
proto.com.ud.xcloud.mt5.proto.Subscribe.prototype.setSblsList = function (value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value)
}

/**
 * @param {!proto.com.ud.xcloud.mt5.proto.QSymbol=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.ud.xcloud.mt5.proto.QSymbol}
 */
proto.com.ud.xcloud.mt5.proto.Subscribe.prototype.addSbls = function (opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.ud.xcloud.mt5.proto.QSymbol, opt_index)
}

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.ud.xcloud.mt5.proto.Subscribe} returns this
 */
proto.com.ud.xcloud.mt5.proto.Subscribe.prototype.clearSblsList = function () {
  return this.setSblsList([])
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.com.ud.xcloud.mt5.proto.Response.prototype.toObject = function (opt_includeInstance) {
    return proto.com.ud.xcloud.mt5.proto.Response.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.com.ud.xcloud.mt5.proto.Response} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.com.ud.xcloud.mt5.proto.Response.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        sbl: jspb.Message.getFieldWithDefault(msg, 1, ''),
        login: jspb.Message.getFieldWithDefault(msg, 2, 0),
        order: jspb.Message.getFieldWithDefault(msg, 3, 0),
        deal: jspb.Message.getFieldWithDefault(msg, 4, 0),
        vol: jspb.Message.getFieldWithDefault(msg, 5, 0),
        price: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
        sl: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
        tp: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
        type: jspb.Message.getFieldWithDefault(msg, 9, 0),
        digit: jspb.Message.getFieldWithDefault(msg, 10, 0),
        status: jspb.Message.getFieldWithDefault(msg, 11, 0),
        closed: jspb.Message.getFieldWithDefault(msg, 12, 0),
        profit: jspb.Message.getFloatingPointFieldWithDefault(msg, 13, 0.0),
        storage: jspb.Message.getFloatingPointFieldWithDefault(msg, 14, 0.0),
        fee: jspb.Message.getFloatingPointFieldWithDefault(msg, 15, 0.0),
        msg: jspb.Message.getFieldWithDefault(msg, 16, ''),
        device: jspb.Message.getFieldWithDefault(msg, 17, 0)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.ud.xcloud.mt5.proto.Response}
 */
proto.com.ud.xcloud.mt5.proto.Response.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.com.ud.xcloud.mt5.proto.Response()
  return proto.com.ud.xcloud.mt5.proto.Response.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.ud.xcloud.mt5.proto.Response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.ud.xcloud.mt5.proto.Response}
 */
proto.com.ud.xcloud.mt5.proto.Response.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {string} */ reader.readString()
        msg.setSbl(value)
        break
      case 2:
        var value = /** @type {number} */ reader.readUint64()
        msg.setLogin(value)
        break
      case 3:
        var value = /** @type {number} */ reader.readUint64()
        msg.setOrder(value)
        break
      case 4:
        var value = /** @type {number} */ reader.readUint64()
        msg.setDeal(value)
        break
      case 5:
        var value = /** @type {number} */ reader.readUint64()
        msg.setVol(value)
        break
      case 6:
        var value = /** @type {number} */ reader.readDouble()
        msg.setPrice(value)
        break
      case 7:
        var value = /** @type {number} */ reader.readDouble()
        msg.setSl(value)
        break
      case 8:
        var value = /** @type {number} */ reader.readDouble()
        msg.setTp(value)
        break
      case 9:
        var value = /** @type {number} */ reader.readInt32()
        msg.setType(value)
        break
      case 10:
        var value = /** @type {number} */ reader.readInt32()
        msg.setDigit(value)
        break
      case 11:
        var value = /** @type {number} */ reader.readInt32()
        msg.setStatus(value)
        break
      case 12:
        var value = /** @type {number} */ reader.readInt32()
        msg.setClosed(value)
        break
      case 13:
        var value = /** @type {number} */ reader.readDouble()
        msg.setProfit(value)
        break
      case 14:
        var value = /** @type {number} */ reader.readDouble()
        msg.setStorage(value)
        break
      case 15:
        var value = /** @type {number} */ reader.readDouble()
        msg.setFee(value)
        break
      case 16:
        var value = /** @type {string} */ reader.readString()
        msg.setMsg(value)
        break
      case 17:
        var value = /** @type {number} */ reader.readInt32()
        msg.setDevice(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.com.ud.xcloud.mt5.proto.Response.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.ud.xcloud.mt5.proto.Response} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.ud.xcloud.mt5.proto.Response.serializeBinaryToWriter = function (message, writer) {
  var f = undefined
  f = /** @type {string} */ jspb.Message.getField(message, 1)
  if (f != null) {
    writer.writeString(1, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 2)
  if (f != null) {
    writer.writeUint64(2, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 3)
  if (f != null) {
    writer.writeUint64(3, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 4)
  if (f != null) {
    writer.writeUint64(4, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 5)
  if (f != null) {
    writer.writeUint64(5, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 6)
  if (f != null) {
    writer.writeDouble(6, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 7)
  if (f != null) {
    writer.writeDouble(7, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 8)
  if (f != null) {
    writer.writeDouble(8, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 9)
  if (f != null) {
    writer.writeInt32(9, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 10)
  if (f != null) {
    writer.writeInt32(10, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 11)
  if (f != null) {
    writer.writeInt32(11, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 12)
  if (f != null) {
    writer.writeInt32(12, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 13)
  if (f != null) {
    writer.writeDouble(13, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 14)
  if (f != null) {
    writer.writeDouble(14, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 15)
  if (f != null) {
    writer.writeDouble(15, f)
  }
  f = /** @type {string} */ jspb.Message.getField(message, 16)
  if (f != null) {
    writer.writeString(16, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 17)
  if (f != null) {
    writer.writeInt32(17, f)
  }
}

/**
 * optional string sbl = 1;
 * @return {string}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.getSbl = function () {
  return /** @type {string} */ jspb.Message.getFieldWithDefault(this, 1, '')
}

/**
 * @param {string} value
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.setSbl = function (value) {
  return jspb.Message.setField(this, 1, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.clearSbl = function () {
  return jspb.Message.setField(this, 1, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.hasSbl = function () {
  return jspb.Message.getField(this, 1) != null
}

/**
 * optional uint64 login = 2;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.getLogin = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 2, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.setLogin = function (value) {
  return jspb.Message.setField(this, 2, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.clearLogin = function () {
  return jspb.Message.setField(this, 2, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.hasLogin = function () {
  return jspb.Message.getField(this, 2) != null
}

/**
 * optional uint64 order = 3;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.getOrder = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 3, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.setOrder = function (value) {
  return jspb.Message.setField(this, 3, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.clearOrder = function () {
  return jspb.Message.setField(this, 3, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.hasOrder = function () {
  return jspb.Message.getField(this, 3) != null
}

/**
 * optional uint64 deal = 4;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.getDeal = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 4, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.setDeal = function (value) {
  return jspb.Message.setField(this, 4, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.clearDeal = function () {
  return jspb.Message.setField(this, 4, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.hasDeal = function () {
  return jspb.Message.getField(this, 4) != null
}

/**
 * optional uint64 vol = 5;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.getVol = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 5, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.setVol = function (value) {
  return jspb.Message.setField(this, 5, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.clearVol = function () {
  return jspb.Message.setField(this, 5, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.hasVol = function () {
  return jspb.Message.getField(this, 5) != null
}

/**
 * optional double price = 6;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.getPrice = function () {
  return /** @type {number} */ jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.setPrice = function (value) {
  return jspb.Message.setField(this, 6, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.clearPrice = function () {
  return jspb.Message.setField(this, 6, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.hasPrice = function () {
  return jspb.Message.getField(this, 6) != null
}

/**
 * optional double sl = 7;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.getSl = function () {
  return /** @type {number} */ jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.setSl = function (value) {
  return jspb.Message.setField(this, 7, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.clearSl = function () {
  return jspb.Message.setField(this, 7, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.hasSl = function () {
  return jspb.Message.getField(this, 7) != null
}

/**
 * optional double tp = 8;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.getTp = function () {
  return /** @type {number} */ jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.setTp = function (value) {
  return jspb.Message.setField(this, 8, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.clearTp = function () {
  return jspb.Message.setField(this, 8, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.hasTp = function () {
  return jspb.Message.getField(this, 8) != null
}

/**
 * optional int32 type = 9;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.getType = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 9, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.setType = function (value) {
  return jspb.Message.setField(this, 9, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.clearType = function () {
  return jspb.Message.setField(this, 9, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.hasType = function () {
  return jspb.Message.getField(this, 9) != null
}

/**
 * optional int32 digit = 10;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.getDigit = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 10, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.setDigit = function (value) {
  return jspb.Message.setField(this, 10, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.clearDigit = function () {
  return jspb.Message.setField(this, 10, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.hasDigit = function () {
  return jspb.Message.getField(this, 10) != null
}

/**
 * optional int32 status = 11;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.getStatus = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 11, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.setStatus = function (value) {
  return jspb.Message.setField(this, 11, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.clearStatus = function () {
  return jspb.Message.setField(this, 11, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.hasStatus = function () {
  return jspb.Message.getField(this, 11) != null
}

/**
 * optional int32 closed = 12;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.getClosed = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 12, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.setClosed = function (value) {
  return jspb.Message.setField(this, 12, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.clearClosed = function () {
  return jspb.Message.setField(this, 12, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.hasClosed = function () {
  return jspb.Message.getField(this, 12) != null
}

/**
 * optional double profit = 13;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.getProfit = function () {
  return /** @type {number} */ jspb.Message.getFloatingPointFieldWithDefault(this, 13, 0.0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.setProfit = function (value) {
  return jspb.Message.setField(this, 13, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.clearProfit = function () {
  return jspb.Message.setField(this, 13, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.hasProfit = function () {
  return jspb.Message.getField(this, 13) != null
}

/**
 * optional double storage = 14;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.getStorage = function () {
  return /** @type {number} */ jspb.Message.getFloatingPointFieldWithDefault(this, 14, 0.0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.setStorage = function (value) {
  return jspb.Message.setField(this, 14, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.clearStorage = function () {
  return jspb.Message.setField(this, 14, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.hasStorage = function () {
  return jspb.Message.getField(this, 14) != null
}

/**
 * optional double fee = 15;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.getFee = function () {
  return /** @type {number} */ jspb.Message.getFloatingPointFieldWithDefault(this, 15, 0.0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.setFee = function (value) {
  return jspb.Message.setField(this, 15, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.clearFee = function () {
  return jspb.Message.setField(this, 15, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.hasFee = function () {
  return jspb.Message.getField(this, 15) != null
}

/**
 * optional string msg = 16;
 * @return {string}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.getMsg = function () {
  return /** @type {string} */ jspb.Message.getFieldWithDefault(this, 16, '')
}

/**
 * @param {string} value
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.setMsg = function (value) {
  return jspb.Message.setField(this, 16, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.clearMsg = function () {
  return jspb.Message.setField(this, 16, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.hasMsg = function () {
  return jspb.Message.getField(this, 16) != null
}

/**
 * optional int32 device = 17;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.getDevice = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 17, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.setDevice = function (value) {
  return jspb.Message.setField(this, 17, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.Response} returns this
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.clearDevice = function () {
  return jspb.Message.setField(this, 17, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.Response.prototype.hasDevice = function () {
  return jspb.Message.getField(this, 17) != null
}

// goog.object.extend(exports, proto.com.ud.xcloud.mt5.proto);
export default proto.com.ud.xcloud.mt5.proto
