// @ts-nocheck
// source: proto/Quote.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

// var jspb = require('google-protobuf');
import * as jspb from 'google-protobuf'
var goog = jspb
var global =
  (typeof globalThis !== 'undefined' && globalThis) ||
  (typeof window !== 'undefined' && window) ||
  (typeof global !== 'undefined' && global) ||
  (typeof self !== 'undefined' && self) ||
  function () {
    return this
  }.call(null) ||
  Function('return this')()

goog.exportSymbol('proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg', null, global)
goog.exportSymbol('proto.com.ud.xcloud.mt5.proto.quote.Tick', null, global)
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.ud.xcloud.mt5.proto.quote.Tick = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.com.ud.xcloud.mt5.proto.quote.Tick, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.ud.xcloud.mt5.proto.quote.Tick.displayName = 'proto.com.ud.xcloud.mt5.proto.quote.Tick'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.repeatedFields_, null)
}
goog.inherits(proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.displayName = 'proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg'
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.com.ud.xcloud.mt5.proto.quote.Tick.prototype.toObject = function (opt_includeInstance) {
    return proto.com.ud.xcloud.mt5.proto.quote.Tick.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.com.ud.xcloud.mt5.proto.quote.Tick} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.com.ud.xcloud.mt5.proto.quote.Tick.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        pos: jspb.Message.getFieldWithDefault(msg, 1, 0),
        price: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
        vol: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.Tick}
 */
proto.com.ud.xcloud.mt5.proto.quote.Tick.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.com.ud.xcloud.mt5.proto.quote.Tick()
  return proto.com.ud.xcloud.mt5.proto.quote.Tick.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.ud.xcloud.mt5.proto.quote.Tick} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.Tick}
 */
proto.com.ud.xcloud.mt5.proto.quote.Tick.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {number} */ reader.readInt32()
        msg.setPos(value)
        break
      case 2:
        var value = /** @type {number} */ reader.readDouble()
        msg.setPrice(value)
        break
      case 3:
        var value = /** @type {number} */ reader.readDouble()
        msg.setVol(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.ud.xcloud.mt5.proto.quote.Tick.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.com.ud.xcloud.mt5.proto.quote.Tick.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.ud.xcloud.mt5.proto.quote.Tick} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.ud.xcloud.mt5.proto.quote.Tick.serializeBinaryToWriter = function (message, writer) {
  var f = undefined
  f = /** @type {number} */ jspb.Message.getField(message, 1)
  if (f != null) {
    writer.writeInt32(1, f)
  }
  f = message.getPrice()
  if (f !== 0.0) {
    writer.writeDouble(2, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 3)
  if (f != null) {
    writer.writeDouble(3, f)
  }
}

/**
 * optional int32 pos = 1;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.quote.Tick.prototype.getPos = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 1, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.Tick} returns this
 */
proto.com.ud.xcloud.mt5.proto.quote.Tick.prototype.setPos = function (value) {
  return jspb.Message.setField(this, 1, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.Tick} returns this
 */
proto.com.ud.xcloud.mt5.proto.quote.Tick.prototype.clearPos = function () {
  return jspb.Message.setField(this, 1, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.quote.Tick.prototype.hasPos = function () {
  return jspb.Message.getField(this, 1) != null
}

/**
 * optional double price = 2;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.quote.Tick.prototype.getPrice = function () {
  return /** @type {number} */ jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.Tick} returns this
 */
proto.com.ud.xcloud.mt5.proto.quote.Tick.prototype.setPrice = function (value) {
  return jspb.Message.setProto3FloatField(this, 2, value)
}

/**
 * optional double vol = 3;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.quote.Tick.prototype.getVol = function () {
  return /** @type {number} */ jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.Tick} returns this
 */
proto.com.ud.xcloud.mt5.proto.quote.Tick.prototype.setVol = function (value) {
  return jspb.Message.setField(this, 3, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.Tick} returns this
 */
proto.com.ud.xcloud.mt5.proto.quote.Tick.prototype.clearVol = function () {
  return jspb.Message.setField(this, 3, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.quote.Tick.prototype.hasVol = function () {
  return jspb.Message.getField(this, 3) != null
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.repeatedFields_ = [4, 5]

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.toObject = function (opt_includeInstance) {
    return proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        ut: jspb.Message.getFieldWithDefault(msg, 1, 0),
        sbl: jspb.Message.getFieldWithDefault(msg, 2, ''),
        digit: jspb.Message.getFieldWithDefault(msg, 3, 0),
        askList: jspb.Message.toObjectList(msg.getAskList(), proto.com.ud.xcloud.mt5.proto.quote.Tick.toObject, includeInstance),
        bidList: jspb.Message.toObjectList(msg.getBidList(), proto.com.ud.xcloud.mt5.proto.quote.Tick.toObject, includeInstance),
        isbuy: jspb.Message.getBooleanFieldWithDefault(msg, 6, false),
        vfree: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg}
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg()
  return proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg}
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {number} */ reader.readFixed64()
        msg.setUt(value)
        break
      case 2:
        var value = /** @type {string} */ reader.readString()
        msg.setSbl(value)
        break
      case 3:
        var value = /** @type {number} */ reader.readUint32()
        msg.setDigit(value)
        break
      case 4:
        var value = new proto.com.ud.xcloud.mt5.proto.quote.Tick()
        reader.readMessage(value, proto.com.ud.xcloud.mt5.proto.quote.Tick.deserializeBinaryFromReader)
        msg.addAsk(value)
        break
      case 5:
        var value = new proto.com.ud.xcloud.mt5.proto.quote.Tick()
        reader.readMessage(value, proto.com.ud.xcloud.mt5.proto.quote.Tick.deserializeBinaryFromReader)
        msg.addBid(value)
        break
      case 6:
        var value = /** @type {boolean} */ reader.readBool()
        msg.setIsbuy(value)
        break
      case 7:
        var value = /** @type {number} */ reader.readDouble()
        msg.setVfree(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.serializeBinaryToWriter = function (message, writer) {
  var f = undefined
  f = message.getUt()
  if (f !== 0) {
    writer.writeFixed64(1, f)
  }
  f = message.getSbl()
  if (f.length > 0) {
    writer.writeString(2, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 3)
  if (f != null) {
    writer.writeUint32(3, f)
  }
  f = message.getAskList()
  if (f.length > 0) {
    writer.writeRepeatedMessage(4, f, proto.com.ud.xcloud.mt5.proto.quote.Tick.serializeBinaryToWriter)
  }
  f = message.getBidList()
  if (f.length > 0) {
    writer.writeRepeatedMessage(5, f, proto.com.ud.xcloud.mt5.proto.quote.Tick.serializeBinaryToWriter)
  }
  f = /** @type {boolean} */ jspb.Message.getField(message, 6)
  if (f != null) {
    writer.writeBool(6, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 7)
  if (f != null) {
    writer.writeDouble(7, f)
  }
}

/**
 * optional fixed64 ut = 1;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.getUt = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 1, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg} returns this
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.setUt = function (value) {
  return jspb.Message.setProto3IntField(this, 1, value)
}

/**
 * optional string sbl = 2;
 * @return {string}
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.getSbl = function () {
  return /** @type {string} */ jspb.Message.getFieldWithDefault(this, 2, '')
}

/**
 * @param {string} value
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg} returns this
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.setSbl = function (value) {
  return jspb.Message.setProto3StringField(this, 2, value)
}

/**
 * optional uint32 digit = 3;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.getDigit = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 3, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg} returns this
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.setDigit = function (value) {
  return jspb.Message.setField(this, 3, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg} returns this
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.clearDigit = function () {
  return jspb.Message.setField(this, 3, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.hasDigit = function () {
  return jspb.Message.getField(this, 3) != null
}

/**
 * repeated Tick ask = 4;
 * @return {!Array<!proto.com.ud.xcloud.mt5.proto.quote.Tick>}
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.getAskList = function () {
  return /** @type{!Array<!proto.com.ud.xcloud.mt5.proto.quote.Tick>} */ jspb.Message.getRepeatedWrapperField(
    this,
    proto.com.ud.xcloud.mt5.proto.quote.Tick,
    4
  )
}

/**
 * @param {!Array<!proto.com.ud.xcloud.mt5.proto.quote.Tick>} value
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg} returns this
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.setAskList = function (value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value)
}

/**
 * @param {!proto.com.ud.xcloud.mt5.proto.quote.Tick=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.Tick}
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.addAsk = function (opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.com.ud.xcloud.mt5.proto.quote.Tick, opt_index)
}

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg} returns this
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.clearAskList = function () {
  return this.setAskList([])
}

/**
 * repeated Tick bid = 5;
 * @return {!Array<!proto.com.ud.xcloud.mt5.proto.quote.Tick>}
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.getBidList = function () {
  return /** @type{!Array<!proto.com.ud.xcloud.mt5.proto.quote.Tick>} */ jspb.Message.getRepeatedWrapperField(
    this,
    proto.com.ud.xcloud.mt5.proto.quote.Tick,
    5
  )
}

/**
 * @param {!Array<!proto.com.ud.xcloud.mt5.proto.quote.Tick>} value
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg} returns this
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.setBidList = function (value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value)
}

/**
 * @param {!proto.com.ud.xcloud.mt5.proto.quote.Tick=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.Tick}
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.addBid = function (opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.com.ud.xcloud.mt5.proto.quote.Tick, opt_index)
}

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg} returns this
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.clearBidList = function () {
  return this.setBidList([])
}

/**
 * optional bool isbuy = 6;
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.getIsbuy = function () {
  return /** @type {boolean} */ jspb.Message.getBooleanFieldWithDefault(this, 6, false)
}

/**
 * @param {boolean} value
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg} returns this
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.setIsbuy = function (value) {
  return jspb.Message.setField(this, 6, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg} returns this
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.clearIsbuy = function () {
  return jspb.Message.setField(this, 6, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.hasIsbuy = function () {
  return jspb.Message.getField(this, 6) != null
}

/**
 * optional double vfree = 7;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.getVfree = function () {
  return /** @type {number} */ jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg} returns this
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.setVfree = function (value) {
  return jspb.Message.setField(this, 7, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg} returns this
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.clearVfree = function () {
  return jspb.Message.setField(this, 7, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.quote.QuoteMsg.prototype.hasVfree = function () {
  return jspb.Message.getField(this, 7) != null
}

// goog.object.extend(exports, proto.com.ud.xcloud.mt5.proto.quote);
export default proto.com.ud.xcloud.mt5.proto.quote
