// @ts-nocheck
// source: proto/UserInfo.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

// var jspb = require('google-protobuf');
import * as jspb from 'google-protobuf'
var goog = jspb
var global =
  (typeof globalThis !== 'undefined' && globalThis) ||
  (typeof window !== 'undefined' && window) ||
  (typeof global !== 'undefined' && global) ||
  (typeof self !== 'undefined' && self) ||
  function () {
    return this
  }.call(null) ||
  Function('return this')()

goog.exportSymbol('proto.com.ud.xcloud.mt5.proto.UserInfo', null, global)
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.ud.xcloud.mt5.proto.UserInfo = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.com.ud.xcloud.mt5.proto.UserInfo, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.ud.xcloud.mt5.proto.UserInfo.displayName = 'proto.com.ud.xcloud.mt5.proto.UserInfo'
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.toObject = function (opt_includeInstance) {
    return proto.com.ud.xcloud.mt5.proto.UserInfo.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.com.ud.xcloud.mt5.proto.UserInfo} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.com.ud.xcloud.mt5.proto.UserInfo.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        login: jspb.Message.getFieldWithDefault(msg, 1, 0),
        group: jspb.Message.getFieldWithDefault(msg, 2, ''),
        phone: jspb.Message.getFieldWithDefault(msg, 3, ''),
        email: jspb.Message.getFieldWithDefault(msg, 4, ''),
        leverage: jspb.Message.getFieldWithDefault(msg, 5, 0),
        agent: jspb.Message.getFieldWithDefault(msg, 6, 0),
        name: jspb.Message.getFieldWithDefault(msg, 7, ''),
        rights: jspb.Message.getFieldWithDefault(msg, 8, 0),
        enable: jspb.Message.getBooleanFieldWithDefault(msg, 9, false)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.ud.xcloud.mt5.proto.UserInfo}
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.com.ud.xcloud.mt5.proto.UserInfo()
  return proto.com.ud.xcloud.mt5.proto.UserInfo.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.ud.xcloud.mt5.proto.UserInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.ud.xcloud.mt5.proto.UserInfo}
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {number} */ reader.readUint64()
        msg.setLogin(value)
        break
      case 2:
        var value = /** @type {string} */ reader.readString()
        msg.setGroup(value)
        break
      case 3:
        var value = /** @type {string} */ reader.readString()
        msg.setPhone(value)
        break
      case 4:
        var value = /** @type {string} */ reader.readString()
        msg.setEmail(value)
        break
      case 5:
        var value = /** @type {number} */ reader.readUint32()
        msg.setLeverage(value)
        break
      case 6:
        var value = /** @type {number} */ reader.readUint32()
        msg.setAgent(value)
        break
      case 7:
        var value = /** @type {string} */ reader.readString()
        msg.setName(value)
        break
      case 8:
        var value = /** @type {number} */ reader.readUint32()
        msg.setRights(value)
        break
      case 9:
        var value = /** @type {boolean} */ reader.readBool()
        msg.setEnable(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.com.ud.xcloud.mt5.proto.UserInfo.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.ud.xcloud.mt5.proto.UserInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.serializeBinaryToWriter = function (message, writer) {
  var f = undefined
  f = message.getLogin()
  if (f !== 0) {
    writer.writeUint64(1, f)
  }
  f = message.getGroup()
  if (f.length > 0) {
    writer.writeString(2, f)
  }
  f = /** @type {string} */ jspb.Message.getField(message, 3)
  if (f != null) {
    writer.writeString(3, f)
  }
  f = /** @type {string} */ jspb.Message.getField(message, 4)
  if (f != null) {
    writer.writeString(4, f)
  }
  f = message.getLeverage()
  if (f !== 0) {
    writer.writeUint32(5, f)
  }
  f = /** @type {number} */ jspb.Message.getField(message, 6)
  if (f != null) {
    writer.writeUint32(6, f)
  }
  f = /** @type {string} */ jspb.Message.getField(message, 7)
  if (f != null) {
    writer.writeString(7, f)
  }
  f = message.getRights()
  if (f !== 0) {
    writer.writeUint32(8, f)
  }
  f = message.getEnable()
  if (f) {
    writer.writeBool(9, f)
  }
}

/**
 * optional uint64 login = 1;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.getLogin = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 1, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.UserInfo} returns this
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.setLogin = function (value) {
  return jspb.Message.setProto3IntField(this, 1, value)
}

/**
 * optional string group = 2;
 * @return {string}
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.getGroup = function () {
  return /** @type {string} */ jspb.Message.getFieldWithDefault(this, 2, '')
}

/**
 * @param {string} value
 * @return {!proto.com.ud.xcloud.mt5.proto.UserInfo} returns this
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.setGroup = function (value) {
  return jspb.Message.setProto3StringField(this, 2, value)
}

/**
 * optional string phone = 3;
 * @return {string}
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.getPhone = function () {
  return /** @type {string} */ jspb.Message.getFieldWithDefault(this, 3, '')
}

/**
 * @param {string} value
 * @return {!proto.com.ud.xcloud.mt5.proto.UserInfo} returns this
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.setPhone = function (value) {
  return jspb.Message.setField(this, 3, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.UserInfo} returns this
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.clearPhone = function () {
  return jspb.Message.setField(this, 3, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.hasPhone = function () {
  return jspb.Message.getField(this, 3) != null
}

/**
 * optional string email = 4;
 * @return {string}
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.getEmail = function () {
  return /** @type {string} */ jspb.Message.getFieldWithDefault(this, 4, '')
}

/**
 * @param {string} value
 * @return {!proto.com.ud.xcloud.mt5.proto.UserInfo} returns this
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.setEmail = function (value) {
  return jspb.Message.setField(this, 4, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.UserInfo} returns this
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.clearEmail = function () {
  return jspb.Message.setField(this, 4, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.hasEmail = function () {
  return jspb.Message.getField(this, 4) != null
}

/**
 * optional uint32 leverage = 5;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.getLeverage = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 5, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.UserInfo} returns this
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.setLeverage = function (value) {
  return jspb.Message.setProto3IntField(this, 5, value)
}

/**
 * optional uint32 agent = 6;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.getAgent = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 6, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.UserInfo} returns this
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.setAgent = function (value) {
  return jspb.Message.setField(this, 6, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.UserInfo} returns this
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.clearAgent = function () {
  return jspb.Message.setField(this, 6, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.hasAgent = function () {
  return jspb.Message.getField(this, 6) != null
}

/**
 * optional string name = 7;
 * @return {string}
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.getName = function () {
  return /** @type {string} */ jspb.Message.getFieldWithDefault(this, 7, '')
}

/**
 * @param {string} value
 * @return {!proto.com.ud.xcloud.mt5.proto.UserInfo} returns this
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.setName = function (value) {
  return jspb.Message.setField(this, 7, value)
}

/**
 * Clears the field making it undefined.
 * @return {!proto.com.ud.xcloud.mt5.proto.UserInfo} returns this
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.clearName = function () {
  return jspb.Message.setField(this, 7, undefined)
}

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.hasName = function () {
  return jspb.Message.getField(this, 7) != null
}

/**
 * optional uint32 rights = 8;
 * @return {number}
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.getRights = function () {
  return /** @type {number} */ jspb.Message.getFieldWithDefault(this, 8, 0)
}

/**
 * @param {number} value
 * @return {!proto.com.ud.xcloud.mt5.proto.UserInfo} returns this
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.setRights = function (value) {
  return jspb.Message.setProto3IntField(this, 8, value)
}

/**
 * optional bool enable = 9;
 * @return {boolean}
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.getEnable = function () {
  return /** @type {boolean} */ jspb.Message.getBooleanFieldWithDefault(this, 9, false)
}

/**
 * @param {boolean} value
 * @return {!proto.com.ud.xcloud.mt5.proto.UserInfo} returns this
 */
proto.com.ud.xcloud.mt5.proto.UserInfo.prototype.setEnable = function (value) {
  return jspb.Message.setProto3BooleanField(this, 9, value)
}

// goog.object.extend(exports, proto.com.ud.xcloud.mt5.proto);
export default proto.com.ud.xcloud.mt5.proto
