server {
  #监听端口
  listen 80;
  #监听地址
  server_name 127.0.0.1;

  #静态资源
  # location / {
  #   # 修改静态文件目录为html/build
  #   root /usr/share/nginx/html;
  #   # 设置默认页
  #   index index.html;
  #   try_files $uri $uri/ /index.html;
  # }

  # 需要在dist目录中创建一个tradingview文件夹
  location /tradingview/ {
    root /usr/share/nginx/html;
    index index.html;
  }

  #cdex项目接口转发
  location ~ /kline/ {
    # proxy_set_header  Host $host;
    proxy_set_header  X-Real-IP $remote_addr;
    proxy_set_header  X-Forwarded-Proto https;
    proxy_set_header  X-Forwarded-For $remote_addr;
    proxy_set_header  X-Forwarded-Host $remote_addr;
    # 代理到后台接口服务
    proxy_pass https://mt.cd-ex.com;
  }

    #cc项目接口转发
  location ~ /socket/ {
    # proxy_set_header  Host $host;
    proxy_set_header  X-Real-IP $remote_addr;
    proxy_set_header  X-Forwarded-Proto https;
    proxy_set_header  X-Forwarded-For $remote_addr;
    proxy_set_header  X-Forwarded-Host $remote_addr;
    # 代理到后台接口服务
    proxy_pass https://traderview.mctzglobals.com;
  }
}
